node.name: "siem-logstash"
path.data: /usr/share/logstash/data
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch:9200"]
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "changeme"
xpack.monitoring.elasticsearch.ssl.certificate_authority: "config/certs/ca/ca.crt"

# API settings
api.http.host: "0.0.0.0"
api.http.port: 9600

# Queue settings
queue.type: memory
queue.page_capacity: 64mb
queue.max_events: 0
queue.max_bytes: 1024mb

# Dead letter queue
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1024mb

# Log level
log.level: info

# Config reload
config.reload.automatic: true
config.reload.interval: 3s
